# Generated by Django 4.1.3 on 2022-11-16 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='sensor_id',
            new_name='sensor',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='measured_temperature',
            new_name='temperature',
        ),
    ]
